BEGIN TRANSACTION;

CREATE TABLE ROLE_PERMISSION (
	ROLE_ID INTEGER NOT NULL REFERENCES ROLE(ID),
	PERMISSION_ID INTEGER NOT NULL REFERENCES PERMISSION(ID),
	PRIMARY KEY(ROLE_ID, PERMISSION_ID)
);

CREATE INDEX ROLE_PERMISSION_ROLE_ID_IDX ON ROLE_PERMISSION (ROLE_ID);

COMMIT;