BEGIN TRANSACTION;

CREATE SEQUENCE SESSION_SEQ START 1;

CREATE TABLE SESSION (
	ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('SESSION_SEQ'),
	USER_ID INTEGER NOT NULL REFERENCES USERS(ID),
	TOKEN CHAR(36) NOT NULL UNIQUE,
	START_TIME TIMESTAMP NOT NULL,
	EXPIRATION_TIME TIMESTAMP NOT NULL
);

CREATE INDEX SESSION_USER_ID_IDX ON SESSION (USER_ID);
CREATE INDEX SESSION_TOKEN_IDX ON SESSION (TOKEN);

COMMIT;