BEGIN TRANSACTION;

CREATE SEQUENCE USERS_SEQ START 1;

CREATE TABLE USERS (
	ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('USERS_SEQ'),
	LOGIN VARCHAR(25) UNIQUE NOT NULL,
	PASSWORD CHAR(64) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	SURNAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(254)
);

CREATE INDEX USERS_LOGIN_IDX ON USERS (LOGIN);
CREATE INDEX USERS_PASSWORD_IDX ON USERS (PASSWORD);

COMMIT;