BEGIN TRANSACTION;

CREATE TABLE USER_ROLE (
	USER_ID INTEGER NOT NULL REFERENCES USERS(ID),
	ROLE_ID INTEGER NOT NULL REFERENCES ROLE(ID),
	PRIMARY KEY(USER_ID, ROLE_ID)
);

CREATE INDEX USER_ROLE_USER_ID_IDX ON USER_ROLE (USER_ID);

COMMIT;